### ISSUE TITLE
 Save changes button should redirect to admin page

### ISSUE THREAD

**Issue by SRKVRM** [nathgoutam93/linkpile-react#12]
### Description

It would be better to redirect to admin page after clicking save changes button in profile page

**Comment by nathgoutam93** [comment]
Thanks for raising the issue , are you willing to work on this issue? 

If yes I would be happy to assign you.

**Comment by SRKVRM** [comment]
Yes please

**Comment by nathgoutam93** [comment]
Okay go for it

**Comment by SRKVRM** [comment]
I'm getting java not installed error while running emulators even after following all the steps.

**Comment by nathgoutam93** [comment]
> I'm getting java not installed error while running emulators even after following all the steps.

which version of java you've installed?
