### ISSUE TITLE
FEATURE: Add more sharing options

### ISSUE THREAD

**Issue by nathgoutam93** [nathgoutam93/linkpile-react#2]
Right now Copy to Clipboard is one and only sharing method .

Add more sharing options like - sharing to social platforms like twitter, Facebook, Instagram etc

**Comment by nathgoutam93** [comment]
Hey there @alceil , are you working on this issue?

**Comment by alceil** [comment]
Ya, tommorow i will raise a pr

**Comment by alceil** [comment]
bro you need a modal popup or something similar to what link tree does @nathgoutam93

**Comment by nathgoutam93** [comment]
@alceil yes modal pop up is what I was thinking to have

**Comment by alceil** [comment]
Hey im getting a auth errror from firebase in emulator mode. Is there any work around for it @nathgoutam93

**Comment by nathgoutam93** [comment]
@alceil make sure you are running the emulators first . Then starting the project .

Emulators do not require any connection to the real firebase project as the credentials are given as test-project

**Comment by alceil** [comment]
I did that but still im not able to login. I just have to run the command npm run emulators right?

**Comment by nathgoutam93** [comment]
> I did that but still im not able to login. I just have to run the command npm run emulators right?

Yes. For the first time  you have to sign up . Then you can login next time .can you show me what error you are getting.

**Comment by alceil** [comment]
Sure

**Comment by nathgoutam93** [comment]
I can replicate this issue by stop running emulators. 
Can you see emulators UI running on localhost:4000 if that is running probably something need to be done from my side.

btw can we continue this conversation on discord or somewhere whenever you open the project.

**Comment by alceil** [comment]
Hey I have raised a pr regarding this issue. Please have a look @nathgoutam93

**Comment by nathgoutam93** [comment]
thanks for the contribution @alceil , I merged the pull request if any changes needed to match with rest of the application theme I'll make those small adjustments
