### ISSUE TITLE
Feat: Add transition to links.

### ISSUE THREAD

**Issue by Olaleye-Blessing** [nathgoutam93/linkpile-react#3]
Links should have a subtle transition when hovered.

**Comment by nathgoutam93** [comment]
if you are willing to work on this , you can make changes into the [src/components/LinkCard.js](https://github.com/nathgoutam93/linkpile-react/blob/6e02f1ebfddab6e3ad3ad459f471833d6cfec7f9/src/components/LinkCard.js) . Which responsible for the links

if you need any help , feel free to ask . @Olaleye-Blessing

**Comment by Olaleye-Blessing** [comment]
I have a question. Is it necessary to install Java for firebase emulators(it's part of contribution guidelines) in order to complete this issue?

**Comment by nathgoutam93** [comment]
To run the project it will require java as the emulators have to run for the data.

I would suggest if you only want to work on this issue and not willing to work on any future issue . 
you can do a trick just import linkCard component to the Home page and give some fake data and make changes.

if you don't want to work on this issue right now it's okay, the priority is low for this issue right now

**Comment by BismeetSingh** [comment]
There seems to be a issue with the firebase exports across operating systems as stated here : https://github.com/firebase/firebase-tools/issues/2421 . Is it possible to have a cross platform compatible export?

**Comment by nathgoutam93** [comment]
> There seems to be a issue with the firebase exports across operating systems as stated here : [firebase/firebase-tools#2421](https://github.com/firebase/firebase-tools/issues/2421) . Is it possible to have a cross platform compatible export?

I'm not sure about that right now , As I don't have a device with MacOs I did'nt check that. Have look how exports can be cross platforms. if I find something I'll get back to you.

**Comment by BismeetSingh** [comment]
How can I generate those exports myself?
