### ISSUE TITLE
[FEATURE] Add Copy To Clipboard Button on Page Component

### ISSUE THREAD

**Issue by nathgoutam93** [nathgoutam93/linkpile-react#8]
### Description

A copy to clipboard button to easily copy the Page link. 

So that if a page visitor want to share the Page to some where they can easily do that

**Comment by A-BMT02** [comment]
I'd like to take a look at this

**Comment by nathgoutam93** [comment]
> I'd like to take a look at this

Sure , go ahead

**Comment by A-BMT02** [comment]
How do you get sign in/login access in the emulator mode ?

**Comment by nathgoutam93** [comment]
Are you 

> How do you get sign in/login access in the emulator mode ?

Are you having problem with sign up/login with emulators or just asking for access?

**Comment by A-BMT02** [comment]
![Screenshot (144)_LI](https://user-images.githubusercontent.com/30394037/154753941-4db5982d-48e9-47ad-851e-e3f0ae693b68.jpg)

**Comment by nathgoutam93** [comment]
> Fixed the issue. Thanks It would be nice if you can add the "npm run emulators" to the CONTRIBUTING.md file so other contributors can set up their environment easily.
> 
> Also just to be clear , for this issue , the button is already on the site right ? You just need the functionality if i'm not mistaken
> 
> ![Screenshot (146)](https://user-images.githubusercontent.com/30394037/154756759-e550b1f5-2e6d-4d38-8773-67c1681ce667.png)

No , the share option is only on the preview page and admin page right now but it is not in the actual page components which will be rendered whenever someone cost your page. 

https://github.com/nathgoutam93/linkpile-react/src/components/pages.js

**Comment by nathgoutam93** [comment]
![IMG_20220219_021108](https://user-images.githubusercontent.com/91387097/154758355-2dcfa840-e052-45a2-9019-854acc68ff8b.jpg)


I wanted something like this , In the Page component but no other sharing options except copy to clipboard @A-BMT02 , I hope you get it what I'm trying to say .

**Comment by nathgoutam93** [comment]
> Noted Do you want the button to just copy the link or you also want it to display a popup showing common social media icons so the user can choose where to share to . I hope i was clear

No just copy to clipboard and an alert would be good saying "link copied" or something similar . 

As the sharing feature on other platforms is being developed by another contributor right now , which will be for admin and preview page .

**Comment by A-BMT02** [comment]
Noted 
I'm working on it

**Comment by nathgoutam93** [comment]
> How do i view the actual page components which will be rendered whenever someone clicks on my link . I want to view it on the browser but i'm getting an error " user not found"

For localhost , the actual link won't work . You have to either type it manually or make the link href="localhost:3000/<your username>"

**Comment by A-BMT02** [comment]
Do you want the icon for the clipboard and the format to be the same as the one on the admin/preview page ?

**Comment by nathgoutam93** [comment]
> Do you want the icon for the clipboard and the format to be the same as the one on the admin/preview page ?

Yes

**Comment by A-BMT02** [comment]
Any thing i can do to make it better ?

**Comment by nathgoutam93** [comment]
> Any thing i can do to make it better ?

I requested some changes , please make those changes

**Comment by nathgoutam93** [comment]
@A-BMT02 will you make the changes I requested on your pull request ?

If you finding any difficulties please let me know I'll make those Changes

**Comment by A-BMT02** [comment]
Yes i am working on it now

**Comment by A-BMT02** [comment]
Sorry i was busy for the past couple of days
